### ISSUE TITLE
/deck - The Fusion and Side deck limits are not obeyed

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#8]
The Fusion and Side decks should only allow 5 cards each. The fusion limit was confirmed at the start of the format, the side deck limit was confirmed by yugioh day.

**Comment by AustinMCrane** [comment]
both should be fixed with the release on may 28th

<img width="1498" alt="Screen Shot 2019-05-28 at 8 13 02 AM" src="https://user-images.githubusercontent.com/12687588/58480686-7138df80-8120-11e9-8919-ddb9694a4395.png">
<img width="1587" alt="Screen Shot 2019-05-28 at 8 13 56 AM" src="https://user-images.githubusercontent.com/12687588/58480737-93326200-8120-11e9-85aa-696e353e5830.png">
